parameters:
#    acmeparentpage.example.class: Acme\parentpageBundle\Example

services:
#    acmeparentpage.example:
#        class: %acmeparentpage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
