parameters:
#    projectbundle_front_end.example.class: Project\bundle\FrontEndBundle\Example

services:
#    projectbundle_front_end.example:
#        class: %projectbundle_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
